### ISSUE TITLE
osbs build-logs shouldn't be blocking on pending build

### ISSUE THREAD

**Issue by pbabinca** [DBuildService/osbs#105]
I believe `osbs build-logs` without `--follow` shouldn't block on the new data and return immediately with current logs. In the case of build in `pending` state this should return empty log.

Currently `osbs build-logs` for `pending` build waits for the logs to appear.

Related https://github.com/DBuildService/osbs/blob/master/osbs/core.py#L171

**Comment by TomasTomecek** [comment]
Right! As far as I remember, the main issue was that openshift returns 500 when the build is in pending state. Let me check.
