### ISSUE TITLE
PrePublishSquashPlugin: metadata aren't stored by default or with dont_load=false

### ISSUE THREAD

**Issue by pbabinca** [DBuildService/osbs#130]
I believe squash plugin should always store metadata even if it doesn't load it back to docker.

**Comment by pbabinca** [comment]
Please delete this one. It should've been created in dock: https://github.com/DBuildService/dock/pull/164

**Comment by TomasTomecek** [comment]
I don't see a delete button.

**Comment by pbabinca** [comment]
Neither do I.
