### ISSUE TITLE
add implicit labels to prod strategy

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/osbs#2]
E.g.:

```json
"Labels": {
    "Architecture": "x86_64",
    "Build_Host": "build.host.redhat.com",
    "Name": "rhel-server-docker",
    "Release": "4",
    "Vendor": "Red Hat, Inc.",
    "Version": "7.1"
}
```
This should be configurable.

**Comment by twaugh** [comment]
Meaning this sort of label?:
  http://docs.openshift.org/latest/architecture/kubernetes_model.html#label

**Comment by TomasTomecek** [comment]
No.

This is pretty confusing because there are actually two types of labels:
 * in k8s, you've just mentioned - they are attached to objects in k8s (we are already using those, check metadata plugin in dock) 
 * and very recently introduced labels in docker (will be in docker 1.6)

this issue is about latter labels. It's about populating build json with values from my original post for dock plugin https://github.com/DBuildService/dock/blob/master/dock/plugins/pre_add_labels_in_df.py

Does this help?

**Comment by twaugh** [comment]
OK, I see.

**Comment by twaugh** [comment]
I'm currently looking at having this in *_inner.json:

```
  {
    "name": "add_labels_in_dockerfile",
    "args": {
      "labels": "{{IMPLICIT_LABELS}}"
    }
  },
```

and introducing a dock_json_merge_arg() method to DockJsonManipulator that takes a dict argument that is updated by the template's dict or, if the template just has a string as in the example above, replaces it.

That way the json template can override the implicit labels if needed.

Does this seem like the right direction to start in?

**Comment by TomasTomecek** [comment]
Wow, this is really neat!

I'm not sure how we should proceed with actual implementation. I'm not in favor of hardcoding `Vendor` and `Build_Host`: maybe these values could be in `osbs.conf` and rest could be specified as an argument (`Release`, `Version`, `Name`, `Architecture`).

What do you think?

**Comment by twaugh** [comment]
I think having `Vendor` and `Build_host` in `osbs.conf` makes sense. Where will the other values ultimately come from?

**Comment by TomasTomecek** [comment]
`Release` and `Version` will need to be set by koji. `Architecture` probably too. `Name` is already provided -- it's component.

**Comment by twaugh** [comment]
OK, `Name` added.

Should the osbs client talk to koji directly to get that, or should `dock`'s `koji` plugin get the information and somehow pass it to the `add_labels_to_dockerfile` plugin?
