### ISSUE TITLE
Use new way of getting build logs

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/osbs#22]
Once this PR https://github.com/openshift/origin/pull/1383 gets merged and released, we need to change the way logs are retrieved.

**Comment by liggitt** [comment]
I think you can already use the proxy method. My pull request makes that the default for `osc build-logs` and will make proxy keep working once the node is secured

**Comment by TomasTomecek** [comment]
We should use this method: https://github.com/openshift/origin/issues/1813#issuecomment-94492848
