### ISSUE TITLE
introduce better exception strategy

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/osbs#43]
Currently, error management within osbs client is pretty weak. It would be great if all exceptions would have same type (and not that some of them are from pycurl, some from python etc.)
E.g.
```
error: (28, \'Operation timed out after 0 milliseconds with 0 out of 0 bytes received\')
error: (7, \'Failed to connect to <ip> port 8443: Connection refused\')
error: (56, \'GnuTLS recv error (-110): The TLS connection was non-properly terminated.\')
```
These should be under some `OsbsConnectionError`, not pycurl.

**Comment by TomasTomecek** [comment]
From my PoV, we should have similar exception hierarchy:
```
OsbsException (parent of all)
 | \
 |   \
 |   OsbsResponseException (response was not 2xx, 3xx)
 |
OsbsConnectionException (we could not connect, or there was some error during connection)
```
@pbabinca what do you think?

**Comment by pbabinca** [comment]
I'd like to see one more level in the hierarchy so I can distinguish between network-related problems and general Osbs problems.

**Comment by TomasTomecek** [comment]
@twaugh 
Tim, thanks for taking this. Feel free to show even early commits so we can discuss the design.

**Comment by twaugh** [comment]
@pbabinca How about renaming `OsbsConnectionException` to `OsbsNetworkException`? Or where would you insert a new level?

**Comment by pbabinca** [comment]
@twaugh I'd like to find out if the problem is infrastructure related - I can try to retry the request - or problem is on some other level and I need to fail in my code.

**Comment by twaugh** [comment]
How about this?:

```
OsbsException (parent of all; you need to fail)
 | \
 |   \
 |   OsbsResponseException (previously OpenshiftException; you need to fail)
 |
OsbsNetworkException (most of http.py exceptions; you can retry)
```

**Comment by pbabinca** [comment]
I guess this could work.

**Comment by twaugh** [comment]
Open to suggestions for improvements.

**Comment by TomasTomecek** [comment]
+1

**Comment by twaugh** [comment]
See what you think about the approach on https://github.com/DBuildService/osbs/compare/master...exceptions.

**Comment by TomasTomecek** [comment]
@twaugh Tim, I really like this! Awesome job. Out of curiosity, do you know if the curl error codes have some textual representation?

**Comment by twaugh** [comment]
They set `args[1]` to a textual description (which we pass through as `message`) but I haven't seen any documentation about them. I based that list only on the names of the error codes, and it probably isn't quite right.

**Comment by TomasTomecek** [comment]
> and it probably isn't quite right

better than having nothing; we can polish over time
