### ISSUE TITLE
Support python 2.5

### ISSUE THREAD

**Issue by pbabinca** [DBuildService/osbs#71]
python 2.5 is only available version on RHEL 5.

**Comment by TomasTomecek** [comment]
![We are Sad](http://m.cdn.blog.hu/sz/szubkultur/image/snoopybabe-cute-sad-cat-1.jpg)

**Comment by bkabrda** [comment]
Why would osbs need to run on RHEL 5? Also, AFAIK, RHEL 5 has Python 2.4.

**Comment by TomasTomecek** [comment]
This is about osbs-client, which will be directly used by koji (which is running on rhel 5 (because...))

**Comment by twaugh** [comment]
FWIW, Travis CI [only supports Python 2.6, 2.7, 3.2, 3.3 and 3.4](http://docs.travis-ci.com/user/languages/python/).

**Comment by pbabinca** [comment]
To clarify my requirement I need python 2.5 support on RHEL 5 system.

**Comment by mikem23** [comment]
The python version on rhel5 is 2.4.3. However I don't think we need this for the koji plugin, we just need to limit the tasks to rhel6 systems or newer.

**Comment by bkabrda** [comment]
Thanks Mike. This means tt should be ok to support Python >= 2.6, since RHEL 6 has Python 2.6. @pbabinca is this ok with you? If so, can we close this?
