### ISSUE TITLE
Update spec file to create pre-releases

### ISSUE THREAD

**Issue by pbabinca** [DBuildService/osbs#91]
I'd like to test pre-released osbs versions but I need to have it as a rpm package. Please modify spec file to create dev pre-releases (with correct upgrade path between versions).

**Comment by bkabrda** [comment]
I'm on it.

**Comment by bkabrda** [comment]
Note: I tried to experiment with Tito, which could make creating post-release RPMs very pleasant, but it has some odd behaviour. With my PR, you need to manually bump value of `%postrelease` to ensure the update path (and of course change the `%commit` macro). I'll try experimenting further with Tito to see if we can make this more automated.
